### ISSUE TITLE
unitConvertor.js always returns the same output

### ISSUE THREAD

**Issue by Zacknetic** [mepzz/LearningNode#2]
- [x] unitConvertor functions return identical outputs regardless of input.
- [ ] consider name change from 'convertor': "A device which converts something into something else." to 'converter' "a person or thing that converts something."

**Comment by Zacknetic** [comment]
Found the issue and made the necessary modifications: 
Please reference Pull Request: #1

**Comment by mepzz** [comment]
PR #1 is accepted and merged. Please review #1  and close.

Function name change is not within the scope of this project. Thank you for your suggestion.

**Comment by Zacknetic** [comment]
PR #1 closed. Thank you!
Closing this issue.
